# yamllint disable rule:line-length
---
name: scorecard

description: run ossf/scorecard and post results to repo security dashboard

runs:
  using: "composite"

  steps:

    - name: Run analysis
      uses: ossf/scorecard-action@0864cf19026789058feabb7e87baa5f140aac736        # v2.3.1
      with:
        results_file: results.sarif
        results_format: sarif

    - name: Upload to code-scanning dashboard
      uses: github/codeql-action/upload-sarif@d39d31e687223d841ef683f52467bd88e9b21c14         # v3.25.3
      with:
        sarif_file: results.sarif
