# yamllint disable rule:line-length
---
name: check

description: Run shellcheck in working-directory.

inputs:

  working-directory:
    description: Set working directory. Default is ./.
    required: false
    default: "."

  shellcheck-version:
    description: set shellcheck version
    required: false
    default: v0.10.0

  shellcheck-exclude:
    description: list of checks to exclude; -e SC2059 -e SC2034 -e SC1090
    required: false
    default: ""

  shellcheck-ignore-paths:
    description: paths to ignore
    required: false
    default: ""

  shellcheck-ignore-names:
    description: specific files to ignore
    required: false
    default: ""

  shellcheck-severity:
    description: severity level; error, warn, info, style (default)
    required: false
    default: "style"

  shellcheck-check-together:
    description: check all files together
    required: false
    default: "no"

  shellcheck-scandir:
    description: directory to scan
    required: false
    default: "."

  shellcheck-additional-files:
    description: check for unusual files
    required: false
    default: ""

  shellcheck-format:
    description: output format; tty (default), gcc, checkstyle, diff, json1, json, quiet
    required: false
    default: "gcc"

runs:
  using: "composite"

  steps:

    - name: write a minimal bash script file so shellcheck always finds something to scan
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: echo "#!/usr/bin/env bash" > ghatoolsactionshellcheckminimummatcher.sh

    - name: check
      uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38          # 2.0.0
      env:
        SHELLCHECK_OPTS: ${{ inputs.shellcheck-exclude }}
      with:
        version: ${{ inputs.shellcheck-version }}
        ignore_paths: ${{ inputs.shellcheck-ignore-paths }}
        ignore_names: ${{ inputs.shellcheck-ignore-names }}
        severity: ${{ inputs.shellcheck-severity }}
        check_together: ${{ inputs.shellcheck-check-together }}
        scandir: ${{ inputs.shellcheck-scandir }}
        additional_files: ${{ inputs.shellcheck-additional-files }}
        format: ${{ inputs.shellcheck-format }}
