# yamllint disable rule:line-length
---
name: run bats test

description: Use bats to perform runtime tests on container.

inputs:

  working-directory:
    description: Set working directory. Default is ./.
    required: false
    default: "."

  registry:
    description: dtr compatible registry
    required: false
    default: docker.io

  path:
    description: Path to the directory containing your Dockerfile and build context
    required: false
    default: .

  image:
    description: Name of image
    required: true

  tag:
    description: Value for tag
    required: false
    default: dev.${GITHUB_SHA:0:7}

  bats-run-container-name:
    description: name for running container
    required: false
    default: container-test

  bats-entry-point:
    description: name of shell ( bash | ash | etc )
    required: false
    default: /bin/bash

  bats-test-path:
    description: Name of folder with bats tests
    required: false
    default: test

runs:
  using: "composite"

  steps:
    - name: bats tests
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        docker run -it -d --name ${{ inputs.bats-run-container-name }} --entrypoint ${{ inputs.bats-entry-point }} ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }}
        bats ${{ inputs.bats-test-path }}
