# yamllint disable rule:line-length
---
name: docker pull

description: pull image from registry

inputs:

  working-directory:
    description: set working directory. Default is ./.
    required: false
    default: "."

  registry:
    description: name of registry
    required: false
    default: docker.io

  image:
    description: name of image
    required: true

  tag:
    description: value for tag
    required: false
    default: dev.${GITHUB_SHA:0:7}

runs:
  using: "composite"

  steps:

    - name: pull image from registry
      shell: bash
      run: docker pull ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }}

    - name: write manifest locally for sbom generation
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: docker image inspect --format='{{index .RepoDigests 0}}' ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }} > manifestid
