# yamllint disable rule:line-length
---
name: lint

description: Run yamllint in working-directory.

inputs:

  working-directory:
    description: Set working directory. Default is ./.
    required: false
    default: "."

runs:
  using: "composite"

  steps:
    - name: yamllint
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: yamllint .
