# yamllint disable rule:line-length
---
name: run trivy docker scan

description: use trivy to scan docker image for vulnerabilities

inputs:

  working-directory:
    description: set working directory. Default is ./.
    required: false
    default: "."

  registry:
    description: dtr compatible registry
    required: false
    default: docker.io

  organization:
    description: dtr compatible organization identified
    required: false
    default: ""

  image:
    description: name of image
    required: true

  tag:
    description: value for tag
    required: false
    default: dev.${GITHUB_SHA:0:7}

  trivy-severity:
    description: trivy scan reporting threshold
    required: false
    default: "LOW,MEDIUM,HIGH,CRITICAL"

  trivy-additional-args:
    description: additional custom command line flags
    required: false
    default: ""

  pipeline-nofail:
    description: do not fail if trivy discovers error, save scan results as job artifact
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: trivy image scan
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        exitcode="--exit-code 1"
        if [[ ${{ inputs.pipeline-nofail == "true" }} ]]; then
          exitcode=""
        fi
        trivy image --severity ${{ inputs.trivy-severity }} \
                    $exitcode \
                    ${{ inputs.trivy-additional-args }} \
                    ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.image }}:${{ inputs.tag }}
