# yamllint disable rule:line-length
---
name: run grype docker scan

description: Use grype to scan docker image for vulnerabilities.

inputs:

  working-directory:
    description: Set working directory. Default is ./.
    required: false
    default: "."

  registry:
    description: dtr compatible registry
    required: false
    default: docker.io

  image:
    description: Name of image
    required: true

  tag:
    description: Value for tag
    required: false
    default: dev.${GITHUB_SHA:0:7}

  grype-severity:
    description: grype scan reporting threshold
    required: false
    default: "medium"

  grype-additional-args:
    description: additional custom command line flags
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: grype image scan
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        grype --fail-on ${{ inputs.grype-severity }} \
              ${{ inputs.grype-additional-args }} \
              ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }}
