# yamllint disable rule:line-length
---
name: hadolint

description: Run hadolint against Dockerfile.

inputs:

  working-directory:
    description: Set working directory. Default is ./.
    required: false
    default: "."

  dockerfile:
    description: Name of dockerfile
    required: false
    default: "Dockerfile"

  hadolint-additional-args:
    description: additional custom command line flags
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: hadolint Dockerfile
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: hadolint ${{ inputs.hadolint-additional-args }} ${{ inputs.dockerfile }}
