# yamllint disable rule:line-length
---
name: setup environment

description: load values from 1password vault

runs:
  using: "composite"

  steps:

    # - name: source $GITHUB_ENV from file using 1password-action/env
    #   uses: ThoughtWorks-DPS/1password-action/env@bef8d7fa03286e10a6b858f4ccc7c9c8be2114e4      # v0.1.1
    #   with:
    #     env-file: op.env

      - name: test
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          DOCKER_LOGIN: op://empc-lab/svc-dockerhub/username
          DOCKER_PASSWORD: op://empc-lab/svc-dockerhub/password
          COSIGN_PASSWORD: op://empc-lab/svc-cosign/passphrase
          SNYK_TOKEN: op://empc-lab/svc-snyk/api-token
          GREN_GITHUB_TOKEN: op://empc-lab/svc-github/access-token
          SLACK_BOT_TOKEN: op://empc-lab/svc-slack/post-bot-token
          CIRCLE_TOKEN: op://empc-lab/svc-circleci/api-token