# yamllint disable rule:line-length
---
name: setup environment

description: load values from 1password vault

inputs:

  OP_SERVICE_ACCOUNT_TOKEN:
    description: credential for managing secure confnig
    required: true

runs:
  using: "composite"

  steps:

    - name: source $GITHUB_ENV from file using 1password-action/env
      uses: ThoughtWorks-DPS/1password-action/env@bef8d7fa03286e10a6b858f4ccc7c9c8be2114e4      # v0.1.1
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ inputs.OP_SERVICE_ACCOUNT_TOKEN }}
      with:
        env-file: op.env
