# yamllint disable rule:line-length
---
name: confirm image registry

description: Confirm image registry credentials

inputs:

  registry:
    description: dtr compatible registry
    required: false
    default: docker.io

runs:
  using: "composite"

  steps:
    - name: login to image registry
      shell: bash
      run: |
        echo 'write to .docker/config.json is secure in ephemeral runtime environment'
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin ${{ inputs.registry }}
