# yamllint disable rule:line-length
---
name: confirm image registry

description: Confirm image registry credentials

inputs:

  registry:
    description: dtr compatible registry
    required: false
    default: docker.io

  registry-login:
    description: registry username
    required: true

  registry-password:
    description: registry password
    required: true

runs:
  using: "composite"

  steps:
    - name: login to image registry
      shell: bash
      run: |
        echo 'write to .docker/config.json is secure in ephemeral runtime environment'
        echo ${{ inputs.registry-password }} | docker login -u ${{ inputs.registry-login }} --password-stdin ${{ inputs.registry }}
