# yamllint disable rule:line-length
---
name: tag docker image

description: tag docker image

inputs:

  working-directory:
    description: set working directory. Default is ./.
    required: false
    default: "."

  registry:
    description: name of registry
    required: false
    default: docker.io

  organization:
    description: dtr compatible organization identified
    required: false
    default: ""

  image:
    description: name of image
    required: true

  current-tag:
    description: value for tag
    required: false
    default: dev.${GITHUB_SHA:0:7}

  release-tag:
    description: value for tag
    required: false
    default: ${GITHUB_REF_NAME}

runs:
  using: "composite"

  steps:
    - name: tag docker image
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: docker tag ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.image }}:${{ inputs.current-tag }} ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.image }}:${{ inputs.release-tag }}
