# yamllint disable rule:line-length
---
name: docker push

description: push image to registry

inputs:

  working-directory:
    description: set working directory. Default is ./.
    required: false
    default: "."

  registry:
    description: name of registry
    required: false
    default: docker.io

  organization:
    description: dtr compatible organization identified
    required: false
    default: ""

  image:
    description: name of image
    required: true

  tag:
    description: value for tag
    required: false
    default: dev.${GITHUB_SHA:0:7}

runs:
  using: "composite"

  steps:
    - name: push image to registry
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: docker push ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.image }}:${{ inputs.tag }}
