# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: integration tests

on:
  workflow_call:

    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        description: 1password vault services account token
        required: false

permissions:
  contents: read

jobs:

  integration-tests:
    name: gha-tools-action integration tests
    runs-on: ubuntu-latest

    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    steps:
      - name: checkout code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b         # v4.1.5

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@143a85f84a90555d121cde2ff5872e393a47ab9f      # v1.0.0
        with:
          version: 2.28.0

      - name: install gha-tools dependencies
        uses: ThoughtWorks-DPS/gha-tools-action/install@main
        with:
          snyk-version: 1.1291.0
          bats-version: 1.11.0
          hadolint-version: 2.12.0
          trivy-version: 0.51.1
          grype-version: 0.77.4
          cosign-version: 2.2.4
          syft-version: 1.4.1
          oras-version: 1.1.0

      - name: test gha-tools-action/install results
        shell: bash
        run: |
          set -exo pipefail
          snyk --version | grep "1.1291.0"
          bats --version | grep "1.11.0"
          hadolint --version | grep "2.12.0"
          trivy --version | grep "0.51.1"
          grype --version | grep "0.77.4"
          cosign version | grep "2.2.4"
          syft --version | grep "1.4.1"
          oras version | grep "1.1.0"
