# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: gha-tools-action static code analysis workflow

on:
  workflow_call:

    inputs:

      working-directory:
        description: Set working directory. Default is ./.
        required: false
        type: string
        default: .

      shellcheck-version:
        description: set shellcheck version
        required: false
        type: string
        default: v0.10.0

      shellcheck-exclude:
        description: list of checks to exclude; -e SC2059 -e SC2034 -e SC1090
        required: false
        type: string
        default: ""

      shellcheck-ignore-paths:
        description: paths to ignore
        required: false
        type: string
        default: ""

      shellcheck-ignore-names:
        description: specific files to ignore
        required: false
        type: string
        default: ""

      shellcheck-severity:
        description: severity level; error, warn, info, style (default)
        required: false
        type: string
        default: "style"

      shellcheck-check-together:
        description: check all files together
        required: false
        type: string
        default: "no"

      shellcheck-scandir:
        description: directory to scan
        required: false
        type: string
        default: "."

      shellcheck-additional-files:
        description: check for unusual files
        required: false
        type: string
        default: ""

      shellcheck-format:
        description: output format; tty (default), gcc, checkstyle, diff, json1, json, quiet
        required: false
        type: string
        default: "gcc"

      before-static-analysis:
        description: Optional steps to run before running static analysis
        required: false
        type: string
        default: echo "none"

      after-static-analysis:
        description: Optional steps to run before after static analysis
        required: false
        type: string
        default: echo "none"

permissions:
  contents: read
  security-events: write

jobs:

  static-code-analysis:
    name: gha-tools-action static code analysis workflow
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b          # v4.1.4

      - name: run custom after-analysis scripts
        working-directory: ${{ inputs.working-directory }}
        shell: bash
        run: ${{ inputs.after-static-analysis }}

      # - name: run custom before-analysis scripts
      #   if: ${{ inputs.before-static-analysis = 'true' }}
      #   uses: .github/actions/test