# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: job container dev build and release

on:
  workflow_call:

    inputs:

      working-directory:
        description: Set working directory. Default is ./.
        required: false
        type: string
        default: .

      before-static-analysis:
        description: Optionally run local actions/before-static-analysis
        required: false
        type: string
        default: ""

      after-static-analysis:
        description: Optional steps to run before after static analysis
        required: false
        type: string
        default: ""

permissions:
  contents: read
  security-events: write

jobs:

  job-container-devl-release:
    name: job container dev build and release
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b          # v4.1.4

      # - name: run custom before-analysis scripts
      #   if: ${{ inputs.before-static-analysis = 'true' }}
      #   uses: .github/actions/before-static-analysis