# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: job-container development release workflow

on:
  workflow_call:

    inputs:

      working-directory:
        description: Set working directory. Default is ./.
        required: false
        type: string
        default: "."

      before-static-analysis:
        description: Optionally call local action before static analysis
        required: false
        type: string
        default: ""

jobs:

  job-container-dev-release:
    name: gha-tools-action dev release of gha container
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b         # v4.1.5

      - name: run custom before-analysis scripts
        if: ${{ inputs.before-static-analysis = 'true' }}
        uses: .github/actions/test
